// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPPVFZRQUblE6cHd_glQpWLGvfXfx8H0A',
    appId: '1:377442875278:web:3b8083036999432751d6df',
    messagingSenderId: '377442875278',
    projectId: 'my-instagram-9f548',
    authDomain: 'my-instagram-9f548.firebaseapp.com',
    storageBucket: 'my-instagram-9f548.appspot.com',
    measurementId: 'G-HL5N2CDNVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi7jemantWcgjll2ixWD8bLi8N7nFBgPo',
    appId: '1:377442875278:android:1fc6f752d670183251d6df',
    messagingSenderId: '377442875278',
    projectId: 'my-instagram-9f548',
    storageBucket: 'my-instagram-9f548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdOhF2BunoGf9d5744vImsSl-HyuV-hoE',
    appId: '1:377442875278:ios:4511d7f6d86e8f9051d6df',
    messagingSenderId: '377442875278',
    projectId: 'my-instagram-9f548',
    storageBucket: 'my-instagram-9f548.appspot.com',
    iosBundleId: 'com.example.myinstagram',
  );
}
